# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives  
  关于: /about
  我: /me

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3: 
    - http://link.hhtjim.com/163/425570952.mp3
    - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: https://image.soutushenqi.com/UserUploadWallpaper_1726403287923.jpg

# 封面区是否显示最新文章
cover_article:
  enable: false

# 是否启用首页logo
logo:
  enable: false
  src: /img/logo.png

# 默认文章封面图（随机调用,支持外链）
cover: 
  - https://gd-hbimg.huaban.com/fb920a6d1466db20eb66b29437da8e51af6b862a553b02-ZFlNK5
  - http://hbimg.huaban.com/fb4fbd1c93b1b3f8ada06da7273d37e745cd40a1bf938-CtW7kR
  - http://hbimg.huaban.com/9a1ff0d2d24bd6f37eda556d457f411b6f19f3351d0aea-aqNEeD
  - http://hbimg.huaban.com/c19805508ba63ba503c79d5dd49ae37766a75f677db91-9gYRnN
  - http://hbimg.huaban.com/8b8901492b5d36a88465c25ec6536d7d916a2f91990f2-iwZi04


# 是否显示Twitter分享卡片图像(图像尺寸要求：1200*600，creatorid不需要带@符号。注意：链接必须是完整url，否则Twitter将无法读取图片信息）
twitterpic:
  enable: false
  src: https://bangdream.moe/img/ident.png
  creatorid: yourtwitteridhere

# 是否使用mathjax
mathjax: false


# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
    # 是否启用
    enable: true

# 是否显示 一言(hitokoto)
hitokoto: false

# 链接(可选:facebook,twitter,github,wechat,email)
links:
    # facebook: /
    # twitter: /
    github: /
    wechat: /
    email: mailto:yx_alkaid@qq.com
  
# 备案
beian: 
    # 是否显示备案信息
    enable: false
    # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
    enableFooter: false
    # 备案号
    beianInfo: 冀ICP备xxxxxxx号
    # 链接地址
    link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否启用评论功能
    enable: false
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: ''
    # 应用秘钥
    clientSecret: ''
    # issue仓库名
    repo: ''
    # Github名
    owner: ''
    # Github名
    admin: ['']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: 

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.jpg

# rss文件
rss: atom.xml

# 要使用版权信息可以在这配置并设定许可方式，可以从 https://creativecommons.org/about/cclicenses/ 查询
copyright:
    enable: false
    license: "CC BY-NC-ND"
